secretKeyFiles - move to JSON
Using a JSON string array. It does not work super great without
modifying more of the parsing logic:

    +(signing.sh:115) nix copy --to 'file:///tmp/nix-shell.9u6yin/nix-test/main/signing/storemultisig?secret-keys=["/tmp/nix-shell.9u6yin/nix-test/main/signing/sk1","/tmp/nix-shell.9u6yin/nix-test/main/signing/sk2"]' /tmp/nix-shell.9u6yin/nix-test/main/signing/store/v6vdfqbxk9q56m6gcvk4h7hyq842y18q-dependencies-top
    error: Cannot parse Nix store 'file:///tmp/nix-shell.9u6yin/nix-test/main/signing/storemultisig?secret-keys=["/tmp/nix-shell.9u6yin/nix-test/main/signing/sk1","/tmp/nix-shell.9u6yin/nix-test/main/signing/sk2"]'
    Try 'nix --help' for more information.
    ++(signing.sh:115) onError
    ++(/home/ninjatrappeur/code-root/github.com/NixOS/nix/tests/functional/common/functions.sh:241) set +x
    signing.sh: test failed at:
    main in signing.sh:115

Besides, the syntax is not great from the CLI: we need to escape the
double quotes provided we want to do some sort of variable
substitution.

    nix copy --to \
      "file://$TEST_ROOT/storemultisig?secret-keys=[\"$TEST_ROOT/sk1\",\"$TEST_ROOT/sk2\"]" \
      "$outPath"

:/